
title: Qa'id Jacobs CV and Resume
url: 'http://resume.qaidjacobs.com'
baseurl: '' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
style: styles-6


#Profile information
name: Qa'id Jacobs
tagline: UX Designer & Creative Director
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: working.qaid@gmail.com
# phone: 012 345 6789
website: qaidjacobs.com #do not add http://
linkedin: qaidjacobs
github: qaid
twitter: '@qaidj'


# Tracker
analytics: UA-64739692-2
#Update all the sections by editing the files inside _includes folder.
